### ISSUE TITLE
Could not build because of missing python3-dev

### ISSUE THREAD

**Issue by marcosoldati** [jupyterhub/the-littlest-jupyterhub#321]
When running the installer I ran into this issue:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 455, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 438, in main
    ensure_user_environment(args.user_requirements_txt_url)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 257, in ensure_user_environment
    'tornado<6.0'
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/conda.py", line 133, in ensure_pip_packages
    ] + packages, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/tljh/user/bin/python', '-m', 'pip', 'install', '--no-cache-dir', 'jupyterhub==0.9.6', 'notebook==5.7.8', 'jupyterlab==0.35.4', 'nteract-on-jupyter==2.0.7', 'nbgitpuller==0.6.1', 'nbresuse==0.3.0', 'ipywidgets==7.4.2', 'tornado<6.0']' returned non-zero exit status 1.
```

Trying to call the command manually unveiled this error:
```
...
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/psutil
    gcc -pthread -B /opt/tljh/user/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=562 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/opt/tljh/user/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
    In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/syslimits.h:7:0,
                     from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:34,
                     from /opt/tljh/user/include/python3.6m/Python.h:11,
                     from psutil/_psutil_common.c:9:
    /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:194:15: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                   ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/opt/tljh/user/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-c2x9uyw7/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ojs_5yct/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-c2x9uyw7/psutil/    
```

Turned out the python3-dev packages were missing on my fresh Ubuntu installation. After a

`sudo apt-get install python3-dev`

everything went smooth. 

If anyone else encounters this issue you may want to add this to the documentation / known_issues.

**Comment by yuvipanda** [comment]
Thanks for opening this. Adding -dev to initial install seems sensible to me.

What version of Ubuntu was this on? Works ok on 18.04 still...

**Comment by yuvipanda** [comment]
On debugging this a little more, it looks like the error is in `fatal error: limits.h: No such file or directory`, which isn't python related. It looks like it's in the libgcc-x-dev packages, from looking at output of `dpkg -S limits.h | grep linux`. Installing gcc *should* install that...

Are you using a minimal ubuntu image by any chance? It looks like the installation still succeeds right now on Ubuntu 18.04

**Comment by marcosoldati** [comment]
Sorry for not getting back to you earlier. 
I am using Ubuntu 18.04.2 LTS. I am using a preconfigured package from my cloud provider. Unfortunately I do not have any hint if they changed anything.

**Comment by cmseal** [comment]
I've had the same issue using a cloud base image of 18.04.2 LTS.  Looking, gcc and libgcc-7-dev were already installed.

Installing python3-dev included dh-python libc-dev-bin libc6-dev libexpat1-dev libpython3-dev libpython3.6-dev linux-libc-dev python3.6-dev.

After installing those, re-running the original TLJH install line worked fine! (just a note about a newer version of conda being available)

HTH.

**Comment by RainnyNightLover** [comment]
meet this for use the Alibaba resource, change it back to ubuntu, fix it!
